#ifndef DEFINE_H_
#define DEFINE_H_

#define SIMPLEMOTION_CONTROL 0
#define ONELEG_CONTROL 1
#define ALLLEGS_CONTROL 2
#define ONELEG_RESET 3
#define ALLLEGS_RESET 4

#define OPENBUS 1
#define CLOSEBUS 2
#define ENABLEMOTOR 3
#define DISABLEMOTOR 4
#define INITAXIS 5
#define GETSTATUS 6
#define CLEARFAULT 7
#define ALLLEGRESET 8
#define ABORTMOTION 9


#endif